### ISSUE TITLE
local fit: Problem with plots

### ISSUE THREAD

**Issue by OthmanB** [OthmanB/Spectra-Simulator-C#2]
using other 00xxx.0.model and a local fit:
e.g.1
 - Likelihoods are read from the file: /home/yuting/Project/TAMCMC-C/test/outputs//00000.0/outputs/00000.0_B_stat_criteria.bin
 - Acceptance rates are read from the file: /home/yuting/Project/TAMCMC-C/test/outputs//00000.0/outputs/00000.0_B_acceptance.txt
Warning: empty y range [-2555.54:-2555.54], adjusting to [-2581.1:-2529.99]
Warning: empty y range [0:0], adjusting to [-1:1]
gsl: ../../gsl-2.6/histogram/init.c:155: ERROR: xmin must be less than xmax
Default GSL error handler invoked.
Aborted (core dumped)

e.g.2
C/test/outputs//00000.0/outputs/00000.0_5_B_acceptance.txt
Warning: empty y range [-3622.69:-3622.69], adjusting to [-3658.91:-3586.46]
Warning: empty y range [0:0], adjusting to [-1:1]
gsl: ../../gsl-2.6/histogram/init.c:155: ERROR: xmin must be less than xmax
Default GSL error handler invoked.
Aborted (core dumped)

**Comment by wtaisabella** [comment]
Adaption for the 00xxx.0.model file before running: I added all the slice, and substitute the  last'#....' session with '# Controls and priors for common parameters' parts in kplr....model example.

**Comment by OthmanB** [comment]
Solved. See: https://github.com/OthmanB/TAMCMC-C/issues/3#issuecomment-564806591
